current_version = "0.1.0"

[[files]]
path = "atskkserv.nimble"
search = "version       = \"{{current_version}}\""
replace = "version       = \"{{new_version}}\""

[[files]]
path = "pyproject.toml"
search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""

[[files]]
path = "docs/conf.py"
search = "release = \"{{current_version}}\""
replace = "release = \"{{new_version}}\""

[[files]]
path = "CHANGELOG.md"
search = """
## v{{current_version}}
"""
replace = """
## v{{new_version}}

{{nowFormat.dateISO}} (Asia/Tokyo)

### 破壊的変更

### 機能の追加、更新

### 不具合等の修正

### その他

## v{{current_version}}
"""

# This file has other replace target, but currently not supported.
[[files]]
path = ".github/release-body.md"
regex = true
search = """
- 更新履歴は https://github.com/attakei/atskkserv/blob/v{{current_version}}/CHANGELOG.md を参照してください。
- リポジトリの差分は (.+)
"""
replace = """
- 更新履歴は https://github.com/attakei/atskkserv/blob/v{{new_version}}/CHANGELOG.md を参照してください。
- リポジトリの差分は https://github.com/attakei/atskkserv/compare/v{{current_version}}...v{{new_version}} を参照してください。
"""

